:stylesheet: CDCU.css

= *CAHIER DES CHARGES*
Hugo CASTELL - Gabin MUNOZ - Matéo PEPIN
v3.0 {localdate}
:sectnums:
:nofooter:
:toc: left
:toc-title: Sommaire

== Présentation du sujet ==

=== Contexte ===
La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. Vous travaillerez à partir d’une application existante « Daily Bank » qu’il faudra adapter aux nouveaux besoins de la banque. +

=== Présentation de l'équipe d'intégration ===

Notre équipe est composée d'un chef de projet, Gabin MUNOZ, et de deux développeurs-intégrateurs, Hugo CASTELL et Matéo PEPIN. +

Les outils utilisés seront : +

** Github : Flexibilité de gestion grâce au versionning et aux issues/milestones
** Discord : Communication instantanée et channels vocaux
** VSCode ou Eclipse pour le développement
** MS Project pour la gestion de projet

NOTE: Nous travaillons l'essentiel du temps hors des séances dédiées pour accélérer le rythme de production des documentations et du code. 

L'équipe mettra en oeuvre ses capacités de développement JAVA, IHM et de gestion de base de données ORACLE.

=== Objectifs ===
L’application doit permettre de gérer des comptes bancaires de dépôt pour des clients préalablement créés. Elle devra permettre de débiter, créditer un compte soit par virement c’est à dire un échange d’argent entre deux comptes distincts mais domiciliés dans le réseau bancaire, soit par une personne physique se présentant devant un guichet. +

Nous produirons des documentations portant sur la gestion du projet mais aussi de la documentation technique et dédiée à l'utilisateur. +

Toutes les documentations seront disponibles sur Github dans un dossier prévu à cet effet.


== Analyse de l'existant ==

.*Version 1


// ANALYSE EXISTANT = ANALYSE BESOINS DANS v1

Dans la version existante, l'utilisateur peut être d'un des status suivants : guichetier ou chef d'agence.
Dans la version existante, le guichetier peut :

** Modifier une information client
** Créer un nouveau client
** Consulter un compte
** Débiter un compte

Et le chef d'agence peut :

** Rendre inactif un client

L'application existante, développée en JAVA, possède déjà une interface graphique. +
La base de données est déjà implémentée, son modèle est relationnel et elle fonctionne sous SQL3. +

// METTRE DIAGRAMME V1
[.text-center]
image::usecase_v0.svg[Diagramme, 400, auto]

Le chef d'agence se place au dessus hiérarchiquement du guichetier, voilà pour pourquoi il hérite de ses droits et en possède d'autres, cette fois-ci propres à lui.

== Analyse des besoins ==

.*Version 2
En partant de la version précédente, les éléments finaux seront :

Pour le guichetier : 

* Générer un relevé mensuel d'un compte en PDF
* Gérer (_CRUD_) les prélèvements automatiques

Toutes ces modifications doivent permettre de rendre les fonctionnalités l'application plus complète.

Chef d'agence :

* Effectuer un débit exceptionnel
* Simuler un emprunt
* Simuler une assurance d'emprunt

Le but de toutes ces modifications est de rendre automatiques les tâches quotidiennes du chef.


// V2 DIAGRAMME
[.text-center]
image::usecase_v0_besoins.svg[Diagramme, 500, auto]

== Analyse des contraintes ==

Contraintes techniques :
* JRE 1.8 (JDK 1.8 pour le développement)
* Encodage en UTF-8
* IDE Visual Studio / Eclipse
* Base de données relationnelle en état cohérent

Contraintes de gestion :
* Rédaction de documentation
* Durée totale du projet de 11 semaines
* Durée alouée au développement de 5 semaines

// juridique et organisationnelle 

== GABIN ==
concurrence :
https://www.furious-squad.com/

Outil de gestion des agences bancaires. 

https://www.capterra.fr/directory/20008/banking-systems/software

un résumé de toutes les solutions pour agence

