:stylesheet: CDCU.css

= *CAHIER DES CHARGES V2/3*
Hugo CASTELL - Gabin MUNOZ - Matéo PEPIN
v3.0 {localdate}
:sectnums:
:nofooter:
:toc: left
:toc-title: Sommaire

== Présentation du sujet ==

=== Contexte ===
La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. Vous travaillerez à partir d’une application existante « Daily Bank » qu’il faudra adapter aux nouveaux besoins de la banque. +

=== Présentation de l'équipe d'intégration ===

Notre équipe est composée d'un chef de projet, Gabin MUNOZ, et de deux développeurs-intégrateurs, Hugo CASTELL et Matéo PEPIN. +

Les outils utilisés seront : +

** Github : Flexibilité de gestion grâce au versionning et aux issues/milestones
** Discord : Communication instantanée et channels vocaux
** VSCode ou Eclipse pour le développement
** MS Project pour la gestion de projet

NOTE: Nous travaillons l'essentiel du temps hors des séances dédiées pour accélérer le rythme de production des documentations et du code. 

L'équipe mettra en oeuvre ses capacités de développement JAVA, IHM et de gestion de base de données ORACLE pour offrir le meilleur des services.

=== Objectifs ===
L’application doit permettre de gérer des comptes bancaires de dépôt pour des clients préalablement créés. Elle devra permettre de débiter, créditer un compte soit par virement c’est à dire un échange d’argent entre deux comptes distincts mais domiciliés dans le réseau bancaire, soit par une personne physique se présentant devant un guichet. +

Nous produirons des documentations portant sur la gestion du projet mais aussi de la documentation technique et dédiée à l'utilisateur. +

Toutes les documentations seront disponibles sur Github dans un dossier prévu à cet effet.

WARNING: Voir Annexe pour plus d'informations sur les documentations.

== Analyse de l'existant ==

.*Version 0

En partant de la version v.0, les éléments implémentés ont été :

Pour le guichetier : 

* Création d'un compte
* Effectuer un virement de compte à compte
* Clôturartion d'un compte
* Crédit d'un compte
* Mise à jour de la fonction Java .débiter()

Chef d'agence :

* Gerer les employés _(CRUD)_

L'application existante, développée en JAVA, possède déjà une interface graphique, qui a été mise à jour. +
La base de données est déjà implémentée, son modèle est relationnel et elle fonctionne sous SQL3 mais son mot de passe a été sécurisée et ses requêtes, optimisées. +

[.text-center]
image::usecase_v0.svg[Diagramme, 400, auto]

Le chef d'agence se place au dessus hiérarchiquement du guichetier, voilà pour pourquoi il hérite de ses droits et en possède d'autres, cette fois-ci propres à lui.

== Analyse des besoins ==

.*Version 2
En partant de la version précédente, les éléments finaux seront :

Pour le guichetier : 

* Générer un relevé mensuel d'un compte en PDF
* Gérer (_CRUD_) les prélèvements automatiques

Toutes ces modifications doivent permettre de rendre les fonctionnalités l'application plus complète.

Chef d'agence :

* Effectuer un débit exceptionnel
* Simuler un emprunt
* Simuler une assurance d'emprunt

Le but de toutes ces modifications est de rendre automatiques les tâches quotidiennes du chef.


// V2 DIAGRAMME
[.text-center]
image::usecase_v2_besoins.svg[Diagramme, 500, auto]

.*Version 3
Dans un objectif à terme, nous espérons optimiser au maximum l'utilisation de la base de données.
Dans le même temps, nous réflechissons à refonte graphique complète de l'application.

== Analyse des contraintes ==

Contraintes techniques :
* JRE 1.8 (JDK 1.8 pour le développement)
* Encodage en UTF-8
* IDE Visual Studio / Eclipse
* Base de données relationnelle en état cohérent
* Refonte IHM dans le but de rendre plus esthétique l'application

Contraintes de gestion :
* Rédaction d'une documentation utilisateur et technique détaillée
* Durée totale du projet de 11 semaines
* Durée alouée au développement de 5 semaines

Contraintes juridiques :
* Manipulation de données bancaires
* Accès aux mots de passe de tiers, de clients
* Manipulation de données sensibles des clients

WARNING: En contact avec des données bancaires et des données personnelles. L'équipe informatique est soumise au RGPD.

NOTE: L'équipe en charge de la base de données est responsable de toute fuite de données éventuelle.

== Brève analyse concurrentielle ==
Il est important de définir le cadre concurrentiel autour de ce projet. +
En effet, cela a son importance dans l'objectif d'innovation et de différentiation des produits existants proposés par d'autres entreprises. +
Parmi les entreprises concurrentes directes de notre produit, on peut retrouver l'entreprise "irisLink" qui innove dans les solutions logicielles de gestion d'agence bancaires et de comptes client. +
https://www.irislink.com +
On peut la définir comme concurrente directe car elle propose des solutions similaires à notre produit.


== Annexe ==

=== Rédaction et documents ===
Ce document fut entièrement rédigé par *Hugo CASTELL* et *Gabin MUNOZ*, membres de l'équipe de développement de l'application. +
Diagrammes UML par *Hugo CASTELL* +
Diagrammes de Gantt par *Matéo PEPIN*

=== Calendrier des livrables ===

[%header,format=csv]
|===
|Nom du livrable,Date de rendu
|Documentation technique v1.0,Semaine 20
|Documentation utilisateur v1.0,Semaine 20
|Cahier de tests v2.0,Semaine 20
|Mise à jour du Gantt,Semaine 20
|Documentation technique v2.0,Semaine 22
|Documentation utilisateur v2.0,Semaine 22
|Cahier de tests v3.0,Semaine 22
|Mise à jour du Gantt,Semaine 22
|Livraison finale,Semaine 23
|Chiffrage du projet,Semaine 23
|Soutenance Orale,Semaine 24
|Bilan du projet,Semaine 24
|===